### PR TITLE
Update conda package to 3.3.0

### PR DESCRIPTION
**Pull request by pmav99**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pmav99** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
Nice to see a new release out! @pmav99 do you want to add yourself as a maintainer here before I merge it?

**Comment by pmav99** [comment]
thank you @ocefpaf but for now i think it is better if you merge it as it is

**Comment by ocefpaf** [comment]
> thank you @ocefpaf but for now i think it is better if you merge it as it is.

No problem. If you change your mind you can use https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username to add yourself to this feedstock.

**Pull request merged**
