### PR TITLE
Patches

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs I added two patches. Teh first one, [`gunicorn.patch`](https://github.com/ocefpaf/pydap-feedstock/blob/42842250669b732af75b22462e936166fa35bd5a/recipe/gunicorn.patch) solves the issue you reported in https://gist.github.com/rsignell-usgs/7c9cf9f88a2f0c920c1a4ee7d7eaf601
(There is no reason to force `gunicorn`, a server only dependency, to use `pydap` in client mode.)

The second patch solves an issue I found while testing this. If you try the test I added here,

```python
from pydap.client import open_url

url = 'http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic'
ds = open_url(url)
```

You will get an error complaining that the `charset` is not set. But according to `webop` own website most endpoints do have have set and we need to `default` to `utf-8`. [`charset.patch`](https://github.com/ocefpaf/pydap-feedstock/blob/42842250669b732af75b22462e936166fa35bd5a/recipe/charset.patch) fixes that too.

I will send those upstream but since we won't get a release anytime soon I am patching here and bumping the build number.

See https://github.com/pydap/pydap/pull/60 and https://github.com/pydap/pydap/pull/59

### CODE REVIEW

**Comment by ocefpaf** [comment]
Needs https://github.com/conda-forge/mechanicalsoup-feedstock/pull/1 to pass Python 3.6

**Comment by rsignell-usgs** [comment]
I just install pydap on Win64 and got this error:
```
---------------------------------------------------------------------------
SSLError                                  Traceback (most recent call last)
<ipython-input-2-42b2bce9af8d> in <module>()
      2 
      3 # Open the dataset using the .dods extension and with request parameters within the URL. Note STATION_ID, BEGIN_DATE, END_DATE, and DATURM within the URL
----> 4 d = open_dods('http://opendap.co-ops.nos.noaa.gov/erddap/tabledap/IOOS_Hourly_Height_Verified_Water_Level.dods?STATION_ID,latitude,longitude,DATUM,BEGIN_DATE,END_DATE,time,WL_VALUE,SIGMA,I,L&STATION_ID="8570283"&DATUM="MLLW"&BEGIN_DATE="20140801"&END_DATE="20140901"')
      5 s = d['s'] # everything is inside 's'

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\site-packages\pydap\client.py in open_dods(url, metadata, application, session)
    101 def open_dods(url, metadata=False, application=None, session=None):
    102     """Open a `.dods` response directly, returning a dataset."""
--> 103     r = GET(url, application, session)
    104     dds, data = r.body.split(b'\nData:\n', 1)
    105     dds = dds.decode(r.content_encoding or 'ascii')

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\site-packages\pydap\net.py in GET(url, application, session)
     18         url = urlunsplit(('', '', path, query, fragment))
     19 
---> 20     return follow_redirect(url, application=application, session=session)
     21 
     22 

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\site-packages\pydap\net.py in follow_redirect(url, application, session, cookies_dict)
     68                                application=application,
     69                                session=session,
---> 70                                cookies_dict=cookies_dict)
     71     else:
     72         return res

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\site-packages\pydap\net.py in follow_redirect(url, application, session, cookies_dict)
     55             req.headers[item] = session.headers[item]
     56 
---> 57     res = req.get_response(application)
     58 
     59     if res.status_code == 302:

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\site-packages\webob\request.py in send(self, application, catch_exc_info)
   1297         else:
   1298             status, headers, app_iter = self.call_application(
-> 1299                 application, catch_exc_info=False)
   1300         return self.ResponseClass(
   1301             status=status, headerlist=list(headers), app_iter=app_iter)

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\site-packages\webob\request.py in call_application(self, application, catch_exc_info)
   1261             captured[:] = [status, headers, exc_info]
   1262             return output.append
-> 1263         app_iter = application(self.environ, start_response)
   1264         if output or not captured:
   1265             try:

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\site-packages\webob\client.py in __call__(self, environ, start_response)
     92         try:
     93             conn.request(environ['REQUEST_METHOD'],
---> 94                          path, body, headers)
     95             res = conn.getresponse()
     96         except socket.timeout:

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\http\client.py in request(self, method, url, body, headers)
   1104     def request(self, method, url, body=None, headers={}):
   1105         """Send a complete request to the server."""
-> 1106         self._send_request(method, url, body, headers)
   1107 
   1108     def _set_content_length(self, body, method):

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\http\client.py in _send_request(self, method, url, body, headers)
   1149             # default charset of iso-8859-1.
   1150             body = _encode(body, 'body')
-> 1151         self.endheaders(body)
   1152 
   1153     def getresponse(self):

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\http\client.py in endheaders(self, message_body)
   1100         else:
   1101             raise CannotSendHeader()
-> 1102         self._send_output(message_body)
   1103 
   1104     def request(self, method, url, body=None, headers={}):

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\http\client.py in _send_output(self, message_body)
    932         del self._buffer[:]
    933 
--> 934         self.send(msg)
    935         if message_body is not None:
    936             self.send(message_body)

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\http\client.py in send(self, data)
    875         if self.sock is None:
    876             if self.auto_open:
--> 877                 self.connect()
    878             else:
    879                 raise NotConnected()

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\http\client.py in connect(self)
   1258 
   1259             self.sock = self._context.wrap_socket(self.sock,
-> 1260                                                   server_hostname=server_hostname)
   1261             if not self._context.check_hostname and self._check_hostname:
   1262                 try:

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\ssl.py in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    375                          suppress_ragged_eofs=suppress_ragged_eofs,
    376                          server_hostname=server_hostname,
--> 377                          _context=self)
    378 
    379     def wrap_bio(self, incoming, outgoing, server_side=False,

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\ssl.py in __init__(self, sock, keyfile, certfile, server_side, cert_reqs, ssl_version, ca_certs, do_handshake_on_connect, family, type, proto, fileno, suppress_ragged_eofs, npn_protocols, ciphers, server_hostname, _context)
    750                         # non-blocking
    751                         raise ValueError("do_handshake_on_connect should not be specified for non-blocking sockets")
--> 752                     self.do_handshake()
    753 
    754             except (OSError, ValueError):

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\ssl.py in do_handshake(self, block)
    986             if timeout == 0.0 and block:
    987                 self.settimeout(None)
--> 988             self._sslobj.do_handshake()
    989         finally:
    990             self.settimeout(timeout)

C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\envs\IOOS3\lib\ssl.py in do_handshake(self)
    631     def do_handshake(self):
    632         """Start the SSL/TLS handshake."""
--> 633         self._sslobj.do_handshake()
    634         if self.context.check_hostname:
    635             if not self.server_hostname:

SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)
```

**Comment by ocefpaf** [comment]
Rich, I am not sure the problem lies with pydap. I believe that is related
to Windows security and conda packages. I did see many related errors when
installing or using conda packages on Windows.

Not sure how to fix though.
@msarahan do you have any tips for us?

**Comment by msarahan** [comment]
Sorry, I have no idea.  I wonder if it had anything to do with the requests problem that happened recently?

https://github.com/conda/conda/issues/3928

ssl.py should be core python, I think.  I wonder what "UNKNOWN PROTOCOL" it is complaining about.

**Comment by ocefpaf** [comment]
Thanks @msarahan! I will investigate this a little bit more.

**Pull request merged**
