### PR TITLE
PyDAP version =  3.5

### PR DESCRIPTION
**Pull request by Mikejmnez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Mikejmnez** [comment]
failed because `docopt-ng` is not conda installable... The previous pydap version 3.4 depended on `docopt` which has long been abandoned. `docopt-ng` is a fork of the original and in full maintenance mode.

**Comment by Mikejmnez** [comment]
I see. Per https://conda-forge.org/docs/maintainer/adding_pkgs/#avoid-external-dependencies, it looks like all dependencies must be available on conda. `docopt-ng` is not. luckly pydap only uses it once. Will move to drop it and try to re-release

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/staged-recipes/pull/27302

**Comment by Mikejmnez** [comment]
> See [conda-forge/staged-recipes#27302](https://github.com/conda-forge/staged-recipes/pull/27302)

Awesome, thanks @ocefpaf! For a minute I thought of reaching out to the `docopt-ng` maintainers to essentially do the same you did on [#conda-forge/staged-recipes#27302](https://github.com/conda-forge/staged-recipes/pull/27302). Are they aware / OK-ed with this? I looked quickly at their repo and I see no reference/discussion about any conda-forge...

**Comment by ocefpaf** [comment]
> Are they aware / OK-ed with this? I looked quickly at their repo and I see no reference/discussion about any conda-forge...

While it is nice to have the package authors involved, third party packaging like in conda-forge, requires only that the package is OSS and with a license that allows packaging. 

> Another thing is that the dependence on `docopt-ng` is minimal as a command line parser when running pydap as a server, and so I wouldn't mind spending some time diverting from `docopt-ng` (and instead use the standard-library `argparser`). But certainly having `docopt-ng` conda-installable would make everything much easier on my end.

Sure. That is probably better in the long run.

**Pull request closed without merging**
